### ISSUE TITLE
Bug report / バグ報告: 

### ISSUE THREAD

**Issue by BannedMan** [saturday06/VRM-Addon-for-Blender#131]
__**Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\VRM_Addon_for_Blender-release\exporter\export_scene.py", line 80, in execute
    vrm_bin = vrm_exporter.export_vrm()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 106, in export_vrm
    self.vrm_meta_to_dic()  # colliderとかmetaとか....
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 2376, in vrm_meta_to_dic
    if collider_object.parent_bone not in self.armature.pose.bones:
AttributeError: 'NoneType' object has no attribute 'parent_bone'_

location: <unknown location>:-1**_

what is this error?

Blender 3.01 and 2.9.1
Nitro AN5
2.3.21 addon version

( select all the things in the model, and relating to the model )
Go to Vrm export
Click on export
wait. and get an error this one ^^^^^^

sorry if this is another my fault

**Comment by saturday06** [comment]
Thanks for reporting. it's a bug. We will fix it soon !!!!

**Comment by saturday06** [comment]
Fixed in 2.3.22 https://github.com/saturday06/VRM_Addon_for_Blender/releases/tag/2_3_22 ! Thanks!

**Comment by BannedMan** [comment]
thank you
