### ISSUE TITLE
Bug report: VRM model not imported

### ISSUE THREAD

**Issue by modforge2** [saturday06/VRM-Addon-for-Blender#176]
**Describe the bug**

**To Reproduce**
just import vrm file in blender.
File - import - vrm

**Expected behavior**
something lagged and only armature imported

**Screenshots**

**Desktop (please complete the following information)**
- OS: Win11, Wind10
- Blender [e.g. 2.93.5, 3.1.2, ...] : 3.4.1
- Addon Version [e.g. 2.4.7, 2.3.8, ...] : 2.10.4

**Additional context**

Error message : 

Python: Traceback (most recent call last):
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\import_scene.py", line 106, in execute
    return create_blend_model(
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\import_scene.py", line 235, in create_blend_model
    ).import_vrm()
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\legacy_vrm_importer.py", line 34, in import_vrm
    self.make_material()
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\abstract_base_vrm_importer.py", line 347, in make_material
    self.reset_material(b_mat)
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\abstract_base_vrm_importer.py", line 326, in reset_material
    shader.clear_node_tree(material.node_tree)
  File "(My Account)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\common\shader.py", line 403, in clear_node_tree
    while node_tree.links:
AttributeError: 'NoneType' object has no attribute 'links'

**Comment by modforge2** [comment]
2.12.1 same

**Comment by saturday06** [comment]
This may be a bug in the add-on. Alternatively, this error occurs when the VRM file you are trying to import is corrupt. Could you please send me ( https://twitter.com/saturday06 ) the VRM file to investigate?

**Comment by comdost** [comment]
Had the same issue, but changing the export settings when exporting the VRM from Unity fixed it (pose freeze, divide vertex buffer), trying different combinations made it work when bringing it to blender.

**Comment by saturday06** [comment]
I could probably fix it with the latest version, but could not reproduce it at hand.
