### ISSUE TITLE
Bug report: 'Object' object has no attribute 'pose_library'

### ISSUE THREAD

**Issue by modforge2** [saturday06/VRM-Addon-for-Blender#234]
When I export this model, It occured error below

```
Python: Traceback (most recent call last):
  File "My Blender Path\3.5\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 96, in export_vrm
    if not self.armature:
  File "My Blender Path\3.5\scripts\addons\VRM_Addon_for_Blender-release\exporter\abstract_base_vrm_exporter.py", line 60, in setup_pose
    for search_pose_index, search_pose_marker in enumerate(
AttributeError: 'Object' object has no attribute 'pose_library'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "My Blender Path\3.5\scripts\addons\VRM_Addon_for_Blender-release\exporter\export_scene.py", line 126, in execute
    is_vrm1 = any(
  File "My Blender Path\3.5\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 120, in export_vrm
    self.hide_outline_modifiers()
  File "My Blender Path\3.5\scripts\addons\VRM_Addon_for_Blender-release\exporter\abstract_base_vrm_exporter.py", line 86, in restore_pose
    if self.context.view_layer.objects.active is not None:
AttributeError: 'Object' object has no attribute 'pose_library'
```

**Comment by saturday06** [comment]
It has been fixed in the latest version of the addon. Please install the latest version.

**Comment by modforge2** [comment]
I'm sorry for confused.
It was crashed when i updating add-on.

Always thx :)
