### ISSUE TITLE
バグ報告: 

### ISSUE THREAD

**Issue by AceBlackCat** [saturday06/VRM-Addon-for-Blender#237]
## バグについて

VRMをインポートできません。

## バグの再現方法

通常の手順でimport vrm をすると起こります。
```
エラーコード
Python: Traceback (most recent call last):
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\import_scene.py", line 222, in execute
    return create_blend_model(
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\import_scene.py", line 291, in create_blend_model
    ).import_vrm()
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\gltf2_addon_vrm_importer.py", line 82, in import_vrm
    self.import_gltf2_with_indices()
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\gltf2_addon_vrm_importer.py", line 1136, in import_gltf2_with_indices
    raise e
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\VRM_Addon_for_Blender-release\importer\gltf2_addon_vrm_importer.py", line 1123, in import_gltf2_with_indices
    bpy.ops.import_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\__init__.py", line 1245, in execute
    return self.import_gltf2(context)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\__init__.py", line 1278, in import_gltf2
    return self.unit_import(self.filepath, import_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\__init__.py", line 1293, in unit_import
    BlenderGlTF.create(gltf_importer)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 37, in create
    BlenderGlTF._create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_gltf.py", line 44, in _create
    BlenderScene.create(gltf)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_scene.py", line 36, in create
    BlenderNode.create_vnode(gltf, 'root')
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 44, in create_vnode
    BlenderNode.create_vnode(gltf, child)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 30, in create_vnode
    obj = BlenderNode.create_object(gltf, vnode_id)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 51, in create_object
    obj = BlenderNode.create_mesh_object(gltf, vnode)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_node.py", line 223, in create_mesh_object
    mesh = BlenderMesh.create(gltf, pynode.mesh, pynode.skin)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 25, in create
    return create_mesh(gltf, mesh_idx, skin_idx)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 46, in create_mesh
    do_primitives(gltf, mesh_idx, skin_idx, mesh, tmp_ob)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 429, in do_primitives
    set_poly_smoothing(gltf, pymesh, mesh, vert_normals, loop_vidxs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\addons\io_scene_gltf2\blender\imp\gltf2_blender_mesh.py", line 612, in set_poly_smoothing
    poly_smooths = np.empty(num_polys, dtype=np.bool)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:113
```

ついこの間まではインポートできていたモデルも突然できなくなりました。
モデルは0.0でも1.0でもどのようなモデルでもインポートできません。

## 期待する動作

インポートできるようにしてほしいです

## スクリーンショット

何か参考になりそうなスクショがあれば添付してください。

## PC環境情報

- OS: [Windows11]
- Blenderのバージョン [3.4.1]
- アドオンのバージョン [2.15.20]

**Comment by saturday06** [comment]
お手数おかけしております。環境にもよるようなのですがBlender 3.4に同梱されているスクリプトのバグが原因で発生するようです。すみませんが、Blenderのバージョンを3.5に上げるか、3.3に下げるかで対応をお願いします。おすすめのバージョンは3.3.5(3.3系の最新版)で、安定していてオススメです。

バグについて詳しく知りたい場合はこちらを参照してください。
- https://github.com/KhronosGroup/glTF-Blender-IO/issues/1844
- https://github.com/KhronosGroup/glTF-Blender-IO/pull/1831
