### ISSUE TITLE
VRM importer crashes with a custom optimizer

### ISSUE THREAD

**Issue by fire** [saturday06/VRM-Addon-for-Blender#31]
**Describe the bug :バグについて**
どのようなバグが起きているのか書いてください。

VRM importer crashes on the load of an optimized Alicia.

**To Reproduce:バグの再現方法**

I have included my modified mesh optimizer source, a win10 executable and source and output vrms.

[Desktop.zip](https://github.com/saturday06/VRM_IMPORTER_for_Blender/files/5660414/Desktop.zip)

Use ` .\gltfpack.exe -i .\AliciaSolid_vrm-0.51.vrm -o .\AliciaSolid_vrm-0.51-opt.vrm`

```
Python: Traceback (most recent call last):
  File "REDACTED\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_IMPORTER_for_Blender-master\__init__.py", line 86, in execute
    blend_model.BlendModel(context, vrm_load.read_vrm(self.filepath, self), self)
  File "REDACTED\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 132, in read_vrm
    node_read(vrm_pydata)
  File "REDACTED\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm_load.py", line 434, in node_read
    vrm_pydata.nodes_dict[i] = vrm2pydata_factory.bone(node)
  File "REDACTED\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_IMPORTER_for_Blender-master\importer\vrm2pydata_factory.py", line 17, in bone
    v_node.position = node["translation"]
KeyError: 'translation'

location: <unknown location>:-1
```

**Expected behavior:期待する動作**

I expect to see no errors and a loaded model of Alicia.

**Screenshots:スクリーンショット**

See the earlier log

**Desktop (please complete the following information):PC環境情報**
 - OS: win 10
 - Blender 2.91
 - Addon ?? Cloned this month

**Additional context :なにか他に書いておきたいことはこちらへ**
I am trying to optimize vrm https://github.com/zeux/meshoptimizer/pull/199

Works in https://vrm-viewer.yukimochi.io/.

![image](https://user-images.githubusercontent.com/32321/101512550-f9ac5900-392f-11eb-984c-689af1f7eeed.png)

**Comment by saturday06** [comment]
Thanks for reporting. `KeyError: 'translation'
` is fixed by https://github.com/saturday06/VRM_IMPORTER_for_Blender/commit/f517a0ddf5873f3d0f82b9475dbd4aaa31852ef3 . But the crash exists yet. Investigating now.

**Comment by fire** [comment]
I have stopped developing that custom optimizer. Thanks.
