### ISSUE TITLE
Bug report: Error on Export

### ISSUE THREAD

**Issue by Elwurd** [saturday06/VRM-Addon-for-Blender#403]
I've made a model and rigged it to the VRM skeleton, but this error pops up and the export fails:

Python: Traceback (most recent call last):
  File "C:\Users\kyled\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 159, in export_vrm
    self.mesh_to_bin_and_dict()
  File "C:\Users\kyled\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 2030, in mesh_to_bin_and_dict
    morph_normal_diff_dict = self.fetch_morph_vertex_normal_difference(
  File "C:\Users\kyled\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\VRM_Addon_for_Blender-release\exporter\legacy_vrm_exporter.py", line 1654, in fetch_morph_vertex_normal_difference
    material = mesh_data.materials[polygon.material_index]
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

It's very possible, even likely that I've just done something wrong but I can't quite figure out what.

**Comment by saturday06** [comment]
Thanks for reporting!
I'll fix this bug over the weekend.

**Comment by Elwurd** [comment]
Oh sorry, I thought I had replied to this! I figured out what was causing it; The exporter errors if you try and export a mesh with no texture; I was making sure the mesh worked fine before I started texturing, but slapping on some plain white materials in blender worked just fine.

**Comment by saturday06** [comment]
This export error (mesh with no texture and etc) was resolved with the latest version v2.20.25 just released. Thank you for your report.
