### ISSUE TITLE
Bug report: addon won't turn on anymore after having been turned off

### ISSUE THREAD

**Issue by Valerie-Bosco** [saturday06/VRM-Addon-for-Blender#505]
## Describe the bug
```py
register_class(...):
Info: Registering panel class: 'VRM_PT_import_unsupported_blender_version_warning', bl_idname 'VRM_PT_import_unsupported_blender_version_warning' has been registered before, unregistering previous
Exception in module register(): C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_57\__init__.py
Traceback (most recent call last):
  File "E:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_57\__init__.py", line 58, in register
    registration.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_57\registration.py", line 454, in register
    bpy.utils.register_class(cls)
RuntimeError: register_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

```py
Exception in module register(): C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_52\__init__.py
Traceback (most recent call last):
  File "E:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_52\__init__.py", line 58, in register
    registration.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_52\registration.py", line 446, in register
    bpy.app.translations.register(
ValueError: bpy.app.translations.register: translations message cache already contains some data for addon 'VRM_Addon_for_Blender-2_20_52'

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_52\editor\mtoon1\panel.py", line 417, in draw
    draw_material(context, self.layout)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\VRM_Addon_for_Blender-2_20_52\editor\mtoon1\panel.py", line 370, in draw_material
    ext = material.vrm_addon_extension
AttributeError: 'Material' object has no attribute 'vrm_addon_extension'
```

no matter how many times i restart blender the same error message appears

## Desktop (please complete the following information)

- OS: windows 11 professional
- Blender 4.1
- Addon Version 2_20_52

**Comment by saturday06** [comment]
Thank you for the report. The latest version, 2.20.60, [resolved another issue you reported](https://github.com/saturday06/VRM-Addon-for-Blender/issues/506), so could you give it a try?

I tried it in almost the same environment as you, and no bugs occurred.

- Windows 11 Professional 22H2
- Blender 4.1.1
- Add-on Version 2_20_52

**Comment by Valerie-Bosco** [comment]
can confirm the error is gone, tested even with a forced reload, the error doesn't happen anymore
