### ISSUE TITLE
Bug report: VRMA bone matrices incorrect

### ISSUE THREAD

**Issue by tdw46** [saturday06/VRM-Addon-for-Blender#547]
## Describe the bug

With the attached VRM file, and VRMA made using the same rig in VRM Posing Desktop, import of VRMA does not produce correct bone transforms.
[VRM Files BONES ONLY.zip](https://github.com/user-attachments/files/16719323/Kigu_VRM.Files.zip)

Also, with the below VRMA made using blender. Playback is not right on the same rig inside unity/VRM Posing Desktop. But is correct when re-importing VRMA to blender on the same rig:
[ANIMATION FILES BONES ONLY.zip](https://github.com/user-attachments/files/16719343/Kigu_CookingComments_8_001_002_PUBLISH_InPlace.zip)
- I included a video and a glb of what the animation is supposed to look like:
https://github.com/user-attachments/assets/d0963acd-737c-4058-81f6-c8898aff0e03
- Versus what it ends up looking like in a Unity based app:
https://github.com/user-attachments/assets/6e8fc3ad-688b-4d63-91cf-ac5bd98acd12

## To Reproduce

1. Export VRMA of attached VRM above from Blender, and try to load in a Unity based application like VRM Posing Desktop. Pose will be wrong.
2. Export VRMA of attached VRM above from Unity Based App like VRM Posing Desktop, and try to load in Blender. Pose will be wrong.
3. Export from blender and reimport into blender and things will be correct. Export from unity and reimport to unity and things will be correct.

## Expected behavior

Animation transforms should work the same in any app that is using the VRMA standard correctly. It seems there is something not working for this particular rig that might indicate a larger problem with the blender exporter/importer.

## Desktop

- OS: Windows 11
- Blender 4.2
- Addon Version: 2.20.82

**Comment by saturday06** [comment]
Thanks for reporting!

This is a bug and will be fixed in a future version.

**Comment by tdw46** [comment]
> Thanks for reporting!
> 
> This is a bug and will be fixed in a future version.

May be related to the work you'll need to do on this. It looks like all actions in my blender file are exporting on my VRM:
![image](https://github.com/user-attachments/assets/b9220fbb-a09c-47b9-a30e-23f67d6460b6)

Would be really nice if we can just expose the gltf settings under the advanced section of the exporter so power users can turn on/off standard gltf features (that aren't part of VRM Extension).

**Comment by Puru-Nekor** [comment]
That is a same bug that I've occured I guess, I was using VRM4U in unreal and I realise the bone works in a very strange way, normaly it starts with a root but instead for this one it starts with the hips
[Animationtest.zip](https://github.com/user-attachments/files/17493616/Animationtest.zip)
if you want to check, here's the file.
the vrma and fbx export are all here
It is exported from blender 4.2.1 LTS
OS: Windows 11
Addon Version: [2.20.87]

**Comment by tdw46** [comment]
@saturday06 Any chance to look at this? I have another 2 test files that have totally wrong transformations when the active action is exported as VRMA.
1. [Test Blender File 1](https://drive.google.com/open?id=1FqR13Mq0AYSUAIt7EMnSddKQTAzUebD_&usp=drive_fs)
2. [Test Blender File 2](https://drive.google.com/open?id=1G1OCNnBllxArw4e9EIgyoWzqnGFkg41Z&usp=drive_fs)
   a. [Test VRM File 2](https://drive.google.com/open?id=1G1gBXd4tt48VNppjZcJTMmDMt4cnOrqz&usp=drive_fs)
   b. [Test VRMA from File 2](https://drive.google.com/open?id=1FfTfHYjArf2rXICIaxqZTZUogUhwn-27&usp=drive_fs)

Test File 2 animation has this kind of pose when in blender:
![Image](https://github.com/user-attachments/assets/2f608f11-9560-477d-96d8-385c77367797)

But the incorrect pose when imported to unity apps like VRM Posing Desktop:
![Image](https://github.com/user-attachments/assets/8046d9da-a0fb-417d-9bf2-057ab8c1012a)

It seems like the VRMA bone transforms are all offset closer to T pose...

Also, related issue: both of the files above can export active actions as VRMA, however test file 1 encounters this error when trying to export at VRM:
```
Python: Traceback (most recent call last):
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\vrm\exporter\export_scene.py", line 306, in export_vrm
    vrm_bytes = vrm_exporter.export_vrm()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\vrm\exporter\vrm1_exporter.py", line 2366, in export_vrm
    export_scene_gltf_result = export_scene_gltf(
                               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\vrm\external\io_scene_gltf2_support.py", line 299, in export_scene_gltf
    return __invoke_export_scene_gltf(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\user_default\vrm\external\io_scene_gltf2_support.py", line 270, in __invoke_export_scene_gltf
    return bpy.ops.export_scene.gltf(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\__init__.py", line 1313, in execute
    res = gltf2_blender_export.save(context, export_settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\export.py", line 37, in save
    json, buffer = __export(export_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\export.py", line 55, in __export
    __gather_gltf(exporter, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\export.py", line 202, in __gather_gltf
    active_scene_idx, scenes, animations = gltf2_blender_gather.gather_gltf2(export_settings)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\gather.py", line 31, in gather_gltf2
    scenes.append(__gather_scene(blender_scene, export_settings))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\cache.py", line 37, in wrapper_cached
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\gather.py", line 123, in __gather_scene
    vtree.add_neutral_bones()
  File "C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\addons_core\io_scene_gltf2\blender\exp\tree.py", line 828, in add_neutral_bones
    self.nodes[n.armature].node.children.append(neutral_bone)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'children'
Location: C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy\ops.py:109
```

**Comment by saturday06** [comment]
@tdw46 Thanks for the detailed research.

The VRMA export is necessary for my own hobby work as well, and I am having trouble with the matrix, so I am working on rewriting the whole thing again.

> Also, related issue: both of the files above can export active actions as VRMA, however test file 1 encounters this error when trying to export at VRM:

This one seems to be a bug in Blender itself, so I will provide feedback there.

**Comment by tdw46** [comment]
@saturday06 I've discovered something potentially useful!

For [Test File 2 above](https://drive.google.com/open?id=1G1OCNnBllxArw4e9EIgyoWzqnGFkg41Z&usp=drive_fs), if I manually rotate the hips to a vertical rotation before VRMA export, the rest of the skeleton plays back as expected! [This VRMA works as expected](https://drive.google.com/open?id=1G4_D9hPquz4wM14FB_-drs9Vm9plNOp0&usp=drive_fs).

![Image](https://github.com/user-attachments/assets/fe4d8713-02ee-4952-937f-845158dcda52)
![Image](https://github.com/user-attachments/assets/bc9af532-c859-4ba7-b464-9e1d346b4d6f)

It appears the problem can be accounted for in `t_pose.py`?

**Comment by tdw46** [comment]
FYI this is fixed [here](https://github.com/saturday06/VRM-Addon-for-Blender/pull/733)

**Comment by saturday06** [comment]
Thanks!
