### ISSUE TITLE
Bug report: BSDF Material Error with glTF 2.0 on Export

### ISSUE THREAD

**Issue by themasmedia** [saturday06/VRM-Addon-for-Blender#661]
## Describe the bug

Error while exporting VRM model with BSDF materials using glTF2 module results in exported model missing shaders.

## To Reproduce

1. Apply BSDF material(s) to model
2. Export vrm with default settings
3. See error

## Expected behavior

BSDF material to export with textures.

## Desktop (please complete the following information)

- OS: Windows 10
- Blender 4.3.0
- Addon Version 2.31.0

## Additional context

Really appreciate all your supportive contribution to the VTuber creator community with this amazing b3d extension!
Here is the Error Message:

ERROR:bl_ext.blender_org.vrm.exporter.vrm0_exporter:[VRM Add-on:ERROR] Failed to import glTF 2.0 Add-on
Traceback (most recent call last):
  File "C:\Users\FrentityStudios\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org\vrm\exporter\vrm0_exporter.py", line 2097, in write_gltf_material
    gltf2_blender_gather_materials = importlib.import_module(module_name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'io_scene_gltf2.blender.exp.material.gltf2_blender_gather_materials'
ERROR:bl_ext.blender_org.vrm.exporter.vrm0_exporter:[VRM Add-on:ERROR] Failed to import glTF 2.0 Add-on
Traceback (most recent call last):
  File "C:\Users\FrentityStudios\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org\vrm\exporter\vrm0_exporter.py", line 2097, in write_gltf_material
    gltf2_blender_gather_materials = importlib.import_module(module_name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'io_scene_gltf2.blender.exp.material.gltf2_blender_gather_materials'
ERROR:bl_ext.blender_org.vrm.exporter.vrm0_exporter:[VRM Add-on:ERROR] Failed to import glTF 2.0 Add-on
Traceback (most recent call last):
  File "C:\Users\FrentityStudios\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org\vrm\exporter\vrm0_exporter.py", line 2097, in write_gltf_material
    gltf2_blender_gather_materials = importlib.import_module(module_name)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_4.3.0.0_x64__ppwjx1n5r4v9t\Blender\4.3\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'io_scene_gltf2.blender.exp.material.gltf2_blender_gather_materials'

**Comment by saturday06** [comment]
Thanks for your report!

The bug has been fixed in the latest version 2.31.1 just released. Please try it!

**Comment by themasmedia** [comment]
You are amazing! Works perfectly again. Thank you!!
