### ISSUE TITLE
Bug report / バグ報告: Unable to load VRM file for some weird reasons

### ISSUE THREAD

**Issue by DerpyMario** [saturday06/VRM-Addon-for-Blender#92]
Hi, i have a problem importing this .vrm file to blender for some unknown reason in blender 2.91:

Traceback (most recent call last):
  File "C:\Users\Homel(PH2)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\import_scene.py", line 47, in execute
    license_validation=True,
  File "C:\Users\Homel(PH2)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\import_scene.py", line 124, in create_blend_model
    addon.make_new_texture_folder,
  File "C:\Users\Homel(PH2)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\legacy_vrm_importer.py", line 35, in import_vrm
    self.make_material()
  File "C:\Users\Homel(PH2)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\abstract_base_vrm_importer.py", line 184, in make_material
    self.build_material_from_mtoon(b_mat, mat)
  File "C:\Users\Homel(PH2)\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\VRM_Addon_for_Blender-release\io_scene_vrm\importer\abstract_base_vrm_importer.py", line 544, in build_material_from_mtoon
    image_index = self.parse_result.json_dict["textures"][tex_index]["source"]
KeyError: 'source'

location: <unknown location>:-1

![image](https://user-images.githubusercontent.com/88537784/157239899-ca91de91-9935-4af8-80d4-cd1550b82fc4.png)

it just gives me only the skeleton and not the mesh...
~~***.zip~~(deleted)

**Comment by DerpyMario** [comment]
what am i supposed to do now?

**Comment by saturday06** [comment]
I had a suspicion that the model you uploaded was ripped, so I contacted VRoid Hub support, and it turned out to be a ripped model.

The ripping of the model violates Article 5 of the VRoid Hub Terms of Use. In some cases, legal action may be taken by pixiv Inc. Please be respectful of the creator’s rights. Due to possible negative impacts, this Issue will be closed.

**Comment by DerpyMario** [comment]
yeah, i had to rip it through memory dump.
